import { ArrowLeft, Navigation, Radio, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useLiveTrip, useTrip } from '../api/hooks';
import { AppShell } from '../app/shell/AppShell';
import { PageHeader } from '../shared/product/PageHeader';
import { StatusNotice } from '../shared/product/StatusNotice';

export function DynamicLiveTripPage() {
  const { tripId = 'TRIP001' } = useParams(); const trip = useTrip(tripId); const live = useLiveTrip(tripId); const data = trip.data; const snapshot = live.data; const loading = trip.isLoading || live.isLoading;
  if (!loading && (!data || !snapshot)) return <AppShell context="Live trip" status="Unavailable"><PageHeader eyebrow={tripId} title="Live trip unavailable" description="Trip not found or live access is unavailable." /><StatusNotice tone="permission" title="Permission boundary">Live state requires a matching trip and trip-scoped authorization.</StatusNotice></AppShell>;
  return <AppShell context={data?.title ?? 'Live trip'} status={snapshot ? `${snapshot.state} · updated 18 s ago` : 'Loading live state'}>
    <PageHeader eyebrow={`${tripId} · Contract-driven live`} title={data ? `${data.route.origin.name} → ${data.route.destination.name}` : 'Loading live trip'} description="Route progress is shown with explicit freshness and confidence." actions={<Link className="button live-exit" to={`/app/trips/${tripId}`}><ArrowLeft aria-hidden="true" /> Trip overview</Link>} />
    {loading ? <StatusNotice tone="loading" title="Loading live trip" /> : null}{data && snapshot ? <div className="dynamic-live-layout">
      <section aria-label="Route and convoy position" className="dynamic-route"><header><div><p className="product-kicker">R001 · Eastbound</p><h2>Route and convoy position</h2></div><span><Radio aria-hidden="true" /> Simulated route projection</span></header><div className="dynamic-route__canvas"><div className="dynamic-route__line" aria-hidden="true" />{snapshot.members.map((member,index) => <div className="dynamic-node" data-confidence={member.confidence} key={member.memberId} style={{ left: `${15 + member.routeProgress * 70}%`, top: `${28 + index * 12}%` }}><i>{index + 1}</i><span><strong>{member.displayName}</strong><small>{member.vehicleLabel}</small></span></div>)}</div><footer><span>Tasco route context · fixture geometry</span><strong>{snapshot.members.length} authorized members</strong></footer></section>
      <aside className="dynamic-live-inspector"><section className="current-instruction"><Navigation aria-hidden="true" /><p className="product-kicker">Current instruction</p><h2>Current instruction</h2><strong>Stay on the planned route.</strong><p>The group is together. Maintain safe formation and avoid catch-up driving.</p></section><section><p className="product-kicker">Member signals</p><h2>Freshness and confidence</h2><ul>{snapshot.members.map((member) => <li key={member.memberId}><div><strong>{member.displayName}</strong><span>{member.vehicleLabel}</span></div><div><span>{member.freshnessLabel}</span><em>confidence {member.confidence}</em></div></li>)}</ul></section><p className="live-privacy"><ShieldCheck aria-hidden="true" /> Location is visible only to authorized trip members.</p></aside>
    </div> : null}
  </AppShell>;
}

export function DynamicSummaryPage() {
  const { tripId = 'TRIP001' } = useParams(); const trip = useTrip(tripId); const data = trip.data; const measured = data?.id === 'TRIP001';
  return <AppShell context="Trip summary" status={measured ? 'Completed · fixture measurement' : 'Unavailable'}><PageHeader eyebrow={`${tripId} · Completed`} title={trip.isLoading ? 'Loading summary' : measured ? 'The convoy is together again.' : 'Summary unavailable'} description="Measured trip facts stay separate from future AI explanation." actions={measured ? <Link className="button button--primary" to={`/app/trips/${tripId}`}>Back to trip</Link> : null} />
    {trip.isLoading ? <StatusNotice tone="loading" title="Loading summary" /> : null}{!trip.isLoading && !measured ? <StatusNotice tone="empty" title="No measured summary is available for this trip fixture">Permission boundary: completed history is visible only for authorized members.</StatusNotice> : null}{measured ? <><p className="summary-disclosure">Fixture measurement · derived from versioned graph and incident events.</p><dl className="dynamic-summary-facts"><div><dt>Confirmed split</dt><dd>1 resolved</dd></div><div><dt>Peak route gap</dt><dd>900 m</dd></div><div><dt>Approved regroup</dt><dd>{data?.route.stops[0]?.place.name ?? 'Minh Châu Rest Stop'}</dd></div><div><dt>Route state</dt><dd>Reconnected</dd></div></dl><section aria-label="Trip timeline" className="dynamic-summary-timeline"><div><p className="product-kicker">Measured event history</p><h2>Trip timeline</h2></div><ol><li><time>08:00</time><i /><div><strong>Departed together</strong><p>Four vehicles connected on R001.</p></div></li><li><time>08:41</time><i /><div><strong>Split confirmed</strong><p>Front and rear components separated at 900 m.</p></div></li><li><time>08:43</time><i /><div><strong>Regroup approved</strong><p>Minh Châu Rest Stop · Tasco POI001.</p></div></li><li><time>08:51</time><i /><div><strong>Reconnected</strong><p>One connected component restored.</p></div></li></ol></section></> : null}
  </AppShell>;
}
